repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: debug-statements
        args: [--branch, main]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
