from excel.utils.excel_dataclass import ExcelData

CONSTANTS_ELEC = [
    ExcelData(
        "UNIDOSE S1",
        "unidose_s1_p_elec",
        "UNIDOSE S1 Electrometer s/n 50095",
        False,
        "Data",
        "O31",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "UNIDOSE E2",
        "unidose_e2_p_elec",
        "UNIDOSE E2 Electrometer s/n 0013",
        False,
        "Data",
        "O32",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "UNIDOSE E3",
        "unidose_e3_p_elec",
        "UNIDOSE E3 Electrometer s/n 0034",
        False,
        "Data",
        "O33",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "UNIDOSE E4",
        "unidose_e4_p_elec",
        "UNIDOSE E4 Electrometer s/n 0035",
        False,
        "Data",
        "O34",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "UNIDOSE E5",
        "unidose_e5_p_elec",
        "UNIDOSE E5 Electrometer s/n 0980",
        False,
        "Data",
        "O35",
        "constant",
        "%0.3f",
        "",
        1,
    ),
]
