from excel.utils.excel_dataclass import ExcelData

CONSTANTS_MARKUS = [
    ExcelData(
        "Markus #1",
        "markus_1_nd",
        "Markus Probe #1 s/n 1705",
        False,
        "Data",
        "I31",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "Markus #2",
        "markus_2_nd",
        "Markus Probe #2 s/n 0434",
        False,
        "Data",
        "I32",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "Markus #4",
        "markus_4_nd",
        "Markus Probe #4 s/n 4249",
        False,
        "Data",
        "I33",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "Markus Savd",
        "markus_savd_nd",
        "Markus Savd Probe s/n 1305",
        False,
        "Data",
        "I34",
        "constant",
        "%0.3f",
        "",
        1,
    ),
]
