from excel.utils.excel_dataclass import ExcelData

CONSTANTS_PROBES = [
    ExcelData(
        "PTW#7",
        "ptw_7_nd",
        "PTW Probe #7 s/n 2525",
        False,
        "Data",
        "C31",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "PTW#2",
        "ptw_2_nd",
        "PTW Probe #2 s/n 1905",
        False,
        "Data",
        "C32",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "PTW#3",
        "ptw_3_nd",
        "PTW Probe #3 s/n 2215",
        False,
        "Data",
        "C33",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "PTW#4",
        "ptw_4_nd",
        "PTW Probe #4 s/n 2216",
        False,
        "Data",
        "C34",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "PTW#5",
        "ptw_5_nd",
        "PTW Probe #5 s/n 2217",
        False,
        "Data",
        "C35",
        "constant",
        "%0.3f",
        "",
        1,
    ),
    ExcelData(
        "PTW#6",
        "ptw_6_nd",
        "PTW Probe #6 s/n 2359",
        False,
        "Data",
        "C36",
        "constant",
        "%0.3f",
        "",
        1,
    ),
]
