from excel.utils.excel_dataclass import ExcelData

CONSTANTS_ELECTRON_FC_ARBUTUS: list = [
    # Arbutus
    ExcelData(
        "Arbutus Electron Solid Water Factor 6E",
        "viarbutus_tb2_electron_6e_fc",
        "Arbutus Electron Solid Water Factor 6E",
        False,
        "Data",
        "AC33",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Arbutus Electron Solid Water Factor 9E",
        "viarbutus_tb2_electron_9e_fc",
        "Arbutus Electron Solid Water Factor 9E",
        False,
        "Data",
        "AD33",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Arbutus Electron Solid Water Factor 12E",
        "viarbutus_tb2_electron_12e_fc",
        "Arbutus Electron Solid Water Factor 12E",
        False,
        "Data",
        "AE33",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Arbutus Electron Solid Water Factor 16E",
        "viarbutus_tb2_electron_16e_fc",
        "Arbutus Electron Solid Water Factor 16E",
        False,
        "Data",
        "AF33",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Arbutus Electron Solid Water Factor 20E",
        "viarbutus_tb2_electron_20e_fc",
        "Arbutus Electron Solid Water Factor 20E",
        False,
        "Data",
        "AG33",
        "constant",
        "%0.1f",
        "",
        1,
    ),
]
