from excel.utils.excel_dataclass import ExcelData

CONSTANTS_ELECTRON_FC_BIRCH: list = [
    # Arbutus
    ExcelData(
        "Birch Electron Solid Water Factor 6E",
        "vibirch_tb1_electron_6e_fc",
        "Birch Electron Solid Water Factor 6E",
        False,
        "Data",
        "AC34",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Birch Electron Solid Water Factor 9E",
        "vibirch_tb1_electron_9e_fc",
        "Birch Electron Solid Water Factor 9E",
        False,
        "Data",
        "AD34",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Birch Electron Solid Water Factor 12E",
        "vibirch_tb1_electron_12e_fc",
        "Birch Electron Solid Water Factor 12E",
        False,
        "Data",
        "AE34",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Birch Electron Solid Water Factor 16E",
        "vibirch_tb1_electron_16e_fc",
        "Birch Electron Solid Water Factor 16E",
        False,
        "Data",
        "AF34",
        "constant",
        "%0.1f",
        "",
        1,
    ),
    ExcelData(
        "Birch Electron Solid Water Factor 20E",
        "vibirch_tb1_electron_20e_fc",
        "Birch Electron Solid Water Factor 20E",
        False,
        "Data",
        "AG34",
        "constant",
        "%0.1f",
        "",
        1,
    ),
]
