from excel.utils.excel_dataclass import ExcelData

CONSTANTS_ELECTRON_FC_FIR: list = [
    # fir
    ExcelData(
        "Fir Electron Solid Water Factor 6E",
        "vifir_tb1_electron_6e_fc",
        "Fir Electron Solid Water Factor 6E",
        False,
        "Data",
        "AC32",
        "constant",
        "%0.1f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Fir Electron Solid Water Factor 9E",
        "vifir_tb1_electron_9e_fc",
        "Fir Electron Solid Water Factor 9E",
        False,
        "Data",
        "AD32",
        "constant",
        "%0.1f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Fir Electron Solid Water Factor 12E",
        "vifir_tb1_electron_12e_fc",
        "Fir Electron Solid Water Factor 12E",
        False,
        "Data",
        "AE32",
        "constant",
        "%0.1f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Fir Electron Solid Water Factor 16E",
        "vifir_tb1_electron_16e_fc",
        "Fir Electron Solid Water Factor 16E",
        False,
        "Data",
        "AF32",
        "constant",
        "%0.1f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Fir Electron Solid Water Factor 20E",
        "vifir_tb1_electron_20e_fc",
        "Fir Electron Solid Water Factor 20E",
        False,
        "Data",
        "AG32",
        "constant",
        "%0.1f",
        "",
        1,
        "",
    ),
]
