from test_lists.monthly.lists import (
    MONTHLY_CYCLE_NO_ELECTRON,
    MONTHLY_CYCLE_W_ELECTRON,
    MONTHLY_NO_ELECTRON,
    MONTHLY_W_ELECTRON,
    QUARTERLY_NO_ELECTRON,
    QUARTERLY_W_ELECTRON,
)

ALL_TEST_LISTS = [
    MONTHLY_CYCLE_W_ELECTRON,
    MONTHLY_CYCLE_NO_ELECTRON,
    MONTHLY_W_ELECTRON,
    MONTHLY_NO_ELECTRON,
    QUARTERLY_NO_ELECTRON,
    QUARTERLY_W_ELECTRON,
]
