from excel.utils.excel_dataclass import ExcelData

CONSTANTS_PHOTON_FC_ARBUTUS: list = [
    ExcelData(
        "Arbutus Photon Solid Water Factor 6X",
        "viarbutus_tb2_photon_6x_fc",
        "Arbutus Photon Solid Water Factor 6X",
        False,
        "Data",
        "U33",
        "constant",
        "%0.2f",
        "",
        1,
    ),
    ExcelData(
        "Arbutus Photon Solid Water Factor 10X",
        "viarbutus_tb2_photon_10x_fc",
        "Arbutus Photon Solid Water Factor 10X",
        False,
        "Data",
        "V33",
        "constant",
        "%0.2f",
        "",
        1,
    ),
    ExcelData(
        "Arbutus Photon Solid Water Factor 15X",
        "viarbutus_tb2_photon_15x_fc",
        "Arbutus Photon Solid Water Factor 15X",
        False,
        "Data",
        "W33",
        "constant",
        "%0.2f",
        "",
        1,
    ),
    ExcelData(
        "Arbutus Photon Solid Water Factor 10XFFF",
        "viarbutus_tb2_photon_10xfff_fc",
        "Arbutus Photon Solid Water Factor 10XFFF",
        False,
        "Data",
        "X33",
        "constant",
        "%0.2f",
        "",
        1,
    ),
]
