from excel.utils.excel_dataclass import ExcelData

CONSTANTS_PHOTON_FC_BIRCH: list = [
    # birch
    ExcelData(
        "Birch Photon Solid Water Factor 6X",
        "vibirch_tb3_photon_6x_fc",
        "Birch Photon Solid Water Factor 6X",
        False,
        "Data",
        "U34",
        "constant",
        "%0.2f",
        "",
        1,
    ),
    ExcelData(
        "Birch Photon Solid Water Factor 10X",
        "vibirch_tb3_photon_10x_fc",
        "Birch Photon Solid Water Factor 10X",
        False,
        "Data",
        "V34",
        "constant",
        "%0.2f",
        "",
        1,
    ),
    ExcelData(
        "Birch Photon Solid Water Factor 15X",
        "vibirch_tb3_photon_15x_fc",
        "Birch Photon Solid Water Factor 15X",
        False,
        "Data",
        "W34",
        "constant",
        "%0.2f",
        "",
        1,
    ),
    ExcelData(
        "Birch Photon Solid Water Factor 10XFFF",
        "vibirch_tb3_photon_10xfff_fc",
        "Birch Photon Solid Water Factor 10XFFF",
        False,
        "Data",
        "X34",
        "constant",
        "%0.2f",
        "",
        1,
    ),
]
