from excel.utils.excel_dataclass import ExcelData

CONSTANTS_PHOTON_FC_CEDAR: list = [
    # cedar
    ExcelData(
        "Cedar Photon Solid Water Factor 6X",
        "vicedar_tb4_photon_6x_fc",
        "Cedar Photon Solid Water Factor 6X",
        False,
        "Data",
        "U35",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Cedar Photon Solid Water Factor 10X",
        "vicedar_tb4_photon_10x_fc",
        "Cedar Photon Solid Water Factor 10X",
        False,
        "Data",
        "V35",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Cedar Photon Solid Water Factor 15X",
        "vicedar_tb4_photon_15x_fc",
        "Cedar Photon Solid Water Factor 15X",
        False,
        "Data",
        "W35",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Cedar Photon Solid Water Factor 10XFFF",
        "vicedar_tb4_photon_10xfff_fc",
        "Cedar Photon Solid Water Factor 10XFFF",
        False,
        "Data",
        "X3",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
]
