from excel.utils.excel_dataclass import ExcelData

CONSTANTS_PHOTON_FC_FIR: list = [
    # fir
    ExcelData(
        "Fir Photon Solid Water Factor 6X",
        "vifir_tb1_photon_6x_fc",
        "Fir Photon Solid Water Factor 6X",
        False,
        "Data",
        "U32",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Fir Photon Solid Water Factor 10X",
        "vifir_tb1_photon_10x_fc",
        "Fir Photon Solid Water Factor 10X",
        False,
        "Data",
        "V32",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Fir Photon Solid Water Factor 15X",
        "vifir_tb1_photon_15x_fc",
        "Fir Photon Solid Water Factor 15X",
        False,
        "Data",
        "W32",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Fir Photon Solid Water Factor 10XFFF",
        "vifir_tb1_photon_10xfff_fc",
        "Fir Photon Solid Water Factor 10XFFF",
        False,
        "Data",
        "X32",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
]
