from excel.utils.excel_dataclass import ExcelData

CONSTANTS_PHOTON_FC_OAK: list = [
    # Oak
    ExcelData(
        "Oak Photon Solid Water Factor 6X",
        "vioak_tb6_photon_6x_fc",
        "Oak Photon Solid Water Factor 6X",
        False,
        "Data",
        "U37",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Oak Photon Solid Water Factor 10X",
        "vioak_tb6_photon_10x_fc",
        "Oak Photon Solid Water Factor 10X",
        False,
        "Data",
        "V37",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Oak Photon Solid Water Factor 15X",
        "vioak_tb6_photon_15x_fc",
        "Oak Photon Solid Water Factor 15X",
        False,
        "Data",
        "W37",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
    ExcelData(
        "Oak Photon Solid Water Factor 10XFFF",
        "vioak_tb6_photon_10xfff_fc",
        "Oak Photon Solid Water Factor 10XFFF",
        False,
        "Data",
        "X37",
        "constant",
        "%0.2f",
        "",
        1,
        "",
    ),
]
