from test_lists.truebeam.monthly.lists import (
    MONTHLY_CYCLE_NO_ELECTRON,
    MONTHLY_CYCLE_W_ELECTRON,
    MONTHLY_NO_ELECTRON,
    MONTHLY_W_ELECTRON,
    QUARTERLY_NO_ELECTRON,
    QUARTERLY_W_ELECTRON,
)

from enum import Enum

MONTHLY_TEST_LISTS = [
    MONTHLY_CYCLE_W_ELECTRON,
    MONTHLY_CYCLE_NO_ELECTRON,
    MONTHLY_W_ELECTRON,
    MONTHLY_NO_ELECTRON,
    QUARTERLY_NO_ELECTRON,
    QUARTERLY_W_ELECTRON,
]


class Monthly(Enum):
    ELECTRON = 0
    NO_ELECTRON = 1
